### ISSUE TITLE
problem with timestamp

### ISSUE THREAD

**Issue by minusmillionaer** [nbj/cockroachdb-laravel#14]
My environment: 
-  cockroachdb server 2.1.0
- Laravel 5.5 
- PHP 7.1

I want to migrate "oauth_auth_codes" from laravel passport (version 4.0). My schema is: 

>Schema::create('oauth_auth_codes', function (Blueprint $table) {
            $table->string('id', 100)->primary();
            $table->uuid('user_id');
            $table->integer('client_id');
            $table->text('scopes')->nullable();
            $table->boolean('revoked');
            $table->dateTime('expires_at')->nullable();
        });

When i'm running `php artisan migrate`, this error occurs:

<img width="1219" alt="bildschirmfoto 2018-11-04 um 21 12 59" src="https://user-images.githubusercontent.com/3305960/47969401-2e75c400-e077-11e8-8a34-138b370b4078.png">

I'm hoping someone else has seen this or a similar error and has some advice. Thanks in advance! Any thoughts?

**Comment by nbj** [comment]
@minusmillionaer Did a quick check on a cockroach 2.0.1 setup (had one running), which ran your migration without any problems. I used the dev-master of the driver, have you tried that, or were you using 0.0.4-alpha? I'm a little hard pressed on time, but I'll try to find time within a couple of days, to test it all out on a cockroach 2.1.0, and hopefully find a solution.

**Comment by minusmillionaer** [comment]
This is now working!
