### ISSUE TITLE
Updates failing?

### ISSUE THREAD

**Issue by leenooks** [nbj/cockroachdb-laravel#20]
I've found another issue when using eloquent timestamps:

```
   Illuminate\Database\QueryException  : SQLSTATE[0A000]: Feature not supported: 7 ERROR:  unimplemented at or near "updated_at"
DETAIL:  source SQL:
update "netmails" set "pkt_date" = $1, "netmails"."updated_at" = $2 where "id" = $3
                                                  ^
HINT:  See: https://github.com/cockroachdb/cockroach/issues/27792 (SQL: update "netmails" set "pkt_date" = 2018-10-15 21:40:53, "netmails"."updated_at" = 2019-05-20 04:51:18 where "id" = 453037869663354881)
```
It seems the issue is that the column is quoted with the table name that Cockroach is not liking?

**Comment by nbj** [comment]
I'll look into this:) Unfortunately I'm a bit stretched on time at the moment, but I'll try to fit it in asap :)

Feel free to submit a PR if you feel like you have a solution :)

**Comment by K12Tech** [comment]
We are also having this issue. For us it is related to soft deletes ( calling model->delete() in code, which is transformed to '_update "deleted_at"=<timestamp>, "table_name"."updated_at"=<timestamp> ..._' .

**Comment by nbj** [comment]
I've been looking a bit into this, but havn't created a real solution to the problem yet :( 

It seems that Laravel's Eloquent\Builder class has been updated to prefix the table name to columns in some queries. This present a problem as cockroach sql does not allow this for some reason, and the Eloquent\Model and Eloquent\Builder classes are not as easily exchangeable as other classes in the Laravel framework.

A workaround at the moment, which really isn't a solution long term, is to edit the `addUpdatedAtColumn()` method in: `Illuminate\Database\Eloquent\Builder.php`

```php
/**
     * Add the "updated at" column to an array of values.
     *
     * @param  array  $values
     * @return array
     */
    protected function addUpdatedAtColumn(array $values)
    {
        if (! $this->model->usesTimestamps() ||
            is_null($this->model->getUpdatedAtColumn())) {
            return $values;
        }

        $column = $this->model->getUpdatedAtColumn();

        $values = array_merge(
            [$column => $this->model->freshTimestampString()],
            $values
        );

        $segments = preg_split('/\s+as\s+/i', $this->query->from);

        // THIS LINE IS THE PROBLEM - Change it to: $qualifiedColumn = $column;
        $qualifiedColumn = end($segments).'.'.$column;

        $values[$qualifiedColumn] = $values[$column];

        unset($values[$column]);

        return $values;
    }

```

**Comment by tankerkiller125** [comment]
I ended up writing my own fix. It requires changing the Model interface that gets extended from the Laravel one to a custom one. I'll see if I can make a PR for this at some point but just in case I've copied the relevant pieces of code below.

(All file would be part of this package)

src/Eloquent/Model.php
```
<?php
namespace Nbj\Cockroach\Eloquent;

use Illuminate\Database\Eloquent\Model as IlluminateModel;

abstract class Model extends IlluminateModel {
    public function newEloquentBuilder($query)
    {
        return new Builder($query);
    }
}
```

src/Eloquent/Builder.php
```
<?php
namespace Nbj\Cockroach\Eloquent;

use Illuminate\Database\Eloquent\Builder as IlluminateBuilder;

class Builder extends IlluminateBuilder {
    protected function addUpdatedAtColumn(array $values)
    {
        if (! $this->model->usesTimestamps() ||
            is_null($this->model->getUpdatedAtColumn())) {
            return $values;
        }

        $column = $this->model->getUpdatedAtColumn();

        $values = array_merge(
            [$column => $this->model->freshTimestampString()],
            $values
        );

        $segments = preg_split('/\s+as\s+/i', $this->query->from);

        $qualifiedColumn = $column;

        $values[$qualifiedColumn] = $values[$column];

        unset($values[$column]);

        return $values;
    }
}
```

src/Auth/User.php
```
<?php

namespace Nbj\Cockroach\Auth;

use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\MustVerifyEmail;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Nbj\Cockroach\Eloquent\Model;

class User extends Model implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword, MustVerifyEmail;
}
```

From here the User.php model for the application would look something like:

```
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Nbj\Cockroach\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable, HasApiTokens;

    protected $fillable = [
        'name', 'email', 'password'
    ];
}
```

And other models would look like:

```
<?php

namespace App;

use Nbj\Cockroach\Eloquent\Model;

class GenericAppModel extends Model
{
    protected $fillable = ['column1', 'column2'];
}
```

**Comment by shahilnissam** [comment]
extend your base model and use this function.

`
// roach update or create mthod	

public static function updateOrCreateRoach(array $attributes = [], $values = []){

        $record = static::where($attributes)->first();
        if(empty($record)){
           $record = new static();
           $record->created_at = Date::now();
        }
        $record->timestamps = false;

        foreach ($values as $key => $val){
            $record->$key = $val;
        }
        $record->updated_at = Date::now();
        $record->save();
        return $record;
    }`

**Comment by leenooks** [comment]
I think this may be address by ajmweb/cockroachdb-laravel@3c6db37
