### ISSUE TITLE
Could not find driver error

### ISSUE THREAD

**Issue by tankerkiller125** [nbj/cockroachdb-laravel#22]
Laravel 7.0 I'm getting a could not find driver error following the exact instructions in the documentation.

**Comment by aleksander-GD** [comment]
@tankerkiller125 Did you close the issue because you found a solution? If you found a solution. It would be grateful to post it here, so others can benefit from it.

**Comment by tankerkiller125** [comment]
Forgot to enable the PDO PGSQL Driver in PHP itself.
