### ISSUE TITLE
Secure Mode?

### ISSUE THREAD

**Issue by tankerkiller125** [nbj/cockroachdb-laravel#3]
Does this work when the CockroachDB is set in secure mode instead of insecure mode?

**Comment by nbj** [comment]
To be honest I have not tried this out yet. I needed a driver for a project, and as CockroachDB connections from PHP goes trough the php-pgsql driver, I rewrote the Postgres driver in Laravel to support Cockroach.

CockroachDBs website does not specify any examples of using the php-pgsql driver in secure mode, but it should be entirely possible, and I recon you could try something out using the documentation of php-pgsql

**Comment by nbj** [comment]
Secure mode works, simply use the new configuration options :)
