### ISSUE TITLE
Can't use because of GPL relicensing

### ISSUE THREAD

**Issue by evantbyrne** [nbj/cockroachdb-laravel#4]
This is a great library and I would like to thank you for your work. However since the code has been relicensed from MIT to GPL, the library cannot be used in non-GPL projects. People that use the GPL are often unaware of this, so I thought I would mention it.

Source: https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL

Cheers,
– Evan

**Comment by nbj** [comment]
Hi @evantbyrne 

Changed the license to MIT, hope this helps you out :)

Best regards
Nikolaj

**Comment by evantbyrne** [comment]
Joyous news indeed!

Thank you,
– Evan
