### ISSUE TITLE
Does this work with certificates instead of username/password?

### ISSUE THREAD

**Issue by nathan-fiscaletti** [nbj/cockroachdb-laravel#5]
It looks like the configuration only has room for a username and password. Is there a way to configure it using a certificate?

**Comment by tokoiwesley** [comment]
Yes it does. It needs a little bit of tweaking.

**Comment by tokoiwesley** [comment]
Edit the default configuration and add the following entries with the paths pointing to the respective certificate locations:
```
    'sslcert'     => env('DB_SSLCERT', '/path/client.root.crt'),
    'sslkey'      => env('DB_SSLKEY', '/path/client.root.key'),
    'sslrootcert' => env('DB_SSLROOTCERT', '/path/ca.crt'),
````
