### ISSUE TITLE
Problem with primary key

### ISSUE THREAD

**Issue by minusmillionaer** [nbj/cockroachdb-laravel#7]
It looks like, i can't set primary in my migrations. I'm using uuids as primary ids and here is my migration: 

> Schema::create('users', function (Blueprint $table) {
            $table->uuid('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
            $table->primary('id');
        });

In my Laravel 5.5 the exception is: 
> Illuminate\Database\QueryException  : SQLSTATE[XX000]: Internal error: 7 ERROR:  multiple primary keys for table "users" are not allowed (SQL: alter table "users" add primary key ("id"))

Is there any solution?

**Comment by nbj** [comment]
I will look into this. It seems like the primary key constraint is auto-created in some cases, which makes it impossible to create again. In some cases it helps to separate table creation and constraint creation into separated migrations.

On another note, why use an uuid as primary key? Cockroach uses serials as a default, which it much faster. Simply use `$table->increments...` or `$table->bigIncrements...` this works flawlessly :)

**Comment by nbj** [comment]
Located part of the issue. Cockroach only allows the primary key to be set while creating the table. It is not possible to add a primary key later on using `alter`
The kicker is, this is exactly what Laravel migrations does when using `->primary()` it creates a second query to alter the table, and this will not work according to the Cockroach documentation.

As for now, the only way you can and a primary key using migrations, is to use `->increments` or `->bigIncrements`. I will be looking into what might be possible to do, with the query builder, if any fix is possible.

**Comment by lemonCMS** [comment]
@minusmillionaer i had the same problem and created a workaround. I have no idea how this fix will hold up, but my initial migration with primary keys works as expected.

You can find it over at https://github.com/lemonCMS/cockroachdb-laravel.

You can test it by adding the following to you composer.json
````json
"repositories": [
    {
      "type": "git",
      "url": "https://github.com/lemonCMS/cockroachdb-laravel.git"
    }
  ],
````
````shell> composer update````

@nbj Great work on this package. you can take a [look](https://github.com/lemonCMS/cockroachdb-laravel/blob/master/src/Cockroach/Grammar/Schema/CockroachGrammar.php) at how i handled this problem and perhaps find the right way to handle this.

unfortunately after running al my migrations i run into another problem with cockoach-db, that is is impossible to use to eloquent ````whereHas()```` function because SQL exists is not fully integrated. So for now i will not continue with cockroach-db, there are just to much limitations.

**Comment by fjeansson** [comment]
Any news on what might be possible to do about this problem?

**Comment by nbj** [comment]
@fjeansson I am working on an implementation of @lemonCMS solution, which fixes the issue. Though this is inherently an issue with cockroachdb not supporting added a primary key after a table has been created.

As for the `whereHas()` issue, this is a bit harder to solve, and as SQL exists still are not fully implemented. So atm. you will need to rewrite all uses of `whereHas()`, this is easy though even if it is irritating.

**Comment by fjeansson** [comment]
Thank you, looking forward to the update.

**Comment by nbj** [comment]
Finally got around to make a fix for this :) @lemonCMS I based it upon the changes you posted, so I was wondering if you have made any more modifications? I tested out your solution, all migration ran flawlessly, but the primary constraints were never created in the database.

**Comment by re-thc** [comment]
Was a solution ever found to fixing the problem key?

**Comment by freite** [comment]
@hc-codersatlas 
https://github.com/freite/cockroachdb-laravel is what i currently use and it works for me.
i do not use serials so that isn't tested

**Comment by nbj** [comment]
@hc-codersatlas sorry for the late reply. Could you please provide me with examples of the isses you are having? It will be easier for me to make the fixes needed. :) The issues first presented by @lemonCMS have been fixed in the current master.

**Comment by re-thc** [comment]
@nbj sorry for the late reply as well :). I just tried it with the latest and seems to be working for now. All good. Thanks.
