### ISSUE TITLE
Issue when seeding tables due to truncate()

### ISSUE THREAD

**Issue by TheDailySpank** [nbj/cockroachdb-laravel#8]
FWIW, when attempting to seed my Cockroach database (where "kw_groups" is the table I am seeding), I got the following error:

```
In Connection.php line 664:
                                                                              
  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "restart"  
  DETAIL:  source SQL:                                                        
  truncate "kw_groups" restart identity                                       
                       ^ (SQL: truncate "kw_groups" restart identity)
```

Looking at the Cockroach (2.0) docs for [TRUNCATE](https://www.cockroachlabs.com/docs/stable/truncate.html#main-content), I did not see an option for "restart identity".

As a workaround, in [CockroachGrammer.php](https://github.com/nbj/cockroachdb-laravel/blob/master/src/Cockroach/Grammar/Query/CockroachGrammar.php), I changed

```
    public function compileTruncate(Builder $query)
    {
        return ['truncate '.$this->wrapTable($query->from).' restart identity' => []];
    }
```

to 

```
    public function compileTruncate(Builder $query)
    {
        return ['truncate ' . $this->wrapTable($query->from) => []];
    }
```

...and now the seeding works as expected including re-running of the seeder on an existing table with data in it.

If I'm doing something wrong, let me know. I'm not really familiar with Postgres let alone all the things Cockroach doesn't quite yet do that Postgres does.

Additional note: I am using use Flynsarmy\CsvSeeder which as part of the run() function in the seeder calls

```
DB::table($this->table)->truncate();
```

so the underlying issue might not be seed specific, but rather related to the truncate() command.

**Comment by nbj** [comment]
Your fix is now implemented in the latest release :)
