### ISSUE TITLE
Use with only Eloquent? 

### ISSUE THREAD

**Issue by nathan-fiscaletti** [nbj/cockroachdb-laravel#9]
I'm using Eloquent with a separate library (not Laravel), and I'd like to use this library as a provider to allow Eloquent to communicate with a Cockroach database. I'm currently using the pgsql driver for this, however there are some discrepancies between the two.

**Comment by nbj** [comment]
Can you provide me with a sample of your project? This driver should work fine with Eloquent eventough you are not using laravel. You might have to look in the service provider class for inspiration on how to register the driver with the Database Capsule. I presume you are pulling illuminate/database into your project?

**Comment by nathan-fiscaletti** [comment]
Maybe I'm missing something. I'm fairly new to using Eloquent for this type of thing. 

This is how I'm currently initializing the connection to my database

```php
//<?php
$capsule = new Illuminate\Database\Capsule\Manager;
$capsule->addConnection([
    'driver' => 'pgsql',
    'host' => $host,
    'port' => $port,
    'database' => $database,
    'username' => $username,
    'password' => $password,
    'charset' => 'utf8',
    'prefix' => '',
    'schema' => $schema,
    'sslmode' => 'prefer',
], $database);
$capsule->setEventDispatcher(new Dispatcher(new Container));
$capsule->bootEloquent();
```

However from looking through the source I'm not seeing it clearly explained how to register a custom database driver using it. I would imagine it would be done through the Capsule Manager, but I'm unsure. Maybe you can tell me what I'm missing.

**Comment by nathan-fiscaletti** [comment]
Using `(new Nbj\Cockroach\CockroachServiceProvider(null))->register();` seemed to work so that now I can use `'driver' => 'cockroach'`. But i'm unsure if this is the proper way to register it.

**Comment by nbj** [comment]
That is one way of doing it, and should work perfectly fine. Another way would be to register the resolver manually like this:

```php
Connection::resolverFor('cockroach', function ($connection, $database, $prefix, $config) {
    $connection = (new CockroachConnector)->connect($config);

    return new CockroachConnection($connection, $database, $prefix, $config);
});
```

**Comment by nathan-fiscaletti** [comment]
Awesome, thanks.
